#ifndef GWPROPERTIES_GLOBAL_H
#define GWPROPERTIES_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(GWPROPERTIES_LIBRARY)
#  define GWPROPERTIESSHARED_EXPORT Q_DECL_EXPORT
#else
#  define GWPROPERTIESSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // GWPROPERTIES_GLOBAL_H
